//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHLVT.Infracture
{
    using System;
    using System.Collections.Generic;
    
    public partial class arkh
    {
        public string ma_cty { get; set; }
        public string ma_kh { get; set; }
        public string loai { get; set; }
        public string ten_kh { get; set; }
        public string ma_so_thue { get; set; }
        public string dia_chi { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string home_page { get; set; }
        public string nguoi_gd { get; set; }
        public string so_tk_nh { get; set; }
        public string ten_nh { get; set; }
        public string tinh_tp_nh { get; set; }
        public string tk { get; set; }
        public string ma_plkh1 { get; set; }
        public string ma_plkh2 { get; set; }
        public string ma_plkh3 { get; set; }
        public string ma_nhkh { get; set; }
        public string ma_tt { get; set; }
        public decimal gh_no { get; set; }
        public string ghi_chu { get; set; }
        public string tinh_dt_nb { get; set; }
        public string khoa_no { get; set; }
        public string isKh { get; set; }
        public string isNcc { get; set; }
        public string isNv { get; set; }
        public string username { get; set; }
        public string sd { get; set; }
        public System.DateTime cdate { get; set; }
        public string cuser { get; set; }
        public System.DateTime ldate { get; set; }
        public string luser { get; set; }
        public string ma_duong { get; set; }
        public string ma_phuong { get; set; }
        public string ma_quan { get; set; }
        public string ma_tp { get; set; }
        public string so_nha { get; set; }
        public string ten_dd { get; set; }
        public string chuc_vu_dd { get; set; }
        public string cmnd_hc { get; set; }
        public System.DateTime ngay_cap { get; set; }
        public string noi_cap { get; set; }
        public string muc_han_tt { get; set; }
        public string dtdd { get; set; }
    }
}
