//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHLVT.Infracture
{
    using System;
    using System.Collections.Generic;
    
    public partial class soct1
    {
        public string ma_cty { get; set; }
        public string stt_rec { get; set; }
        public string stt_rec0 { get; set; }
        public string ma_vt { get; set; }
        public string ma_kho { get; set; }
        public decimal so_luong { get; set; }
        public string dvt { get; set; }
        public decimal so_luong_qd { get; set; }
        public decimal gia_nt2 { get; set; }
        public decimal gia2 { get; set; }
        public decimal tien_nt2 { get; set; }
        public decimal tien2 { get; set; }
        public decimal tl_ck { get; set; }
        public decimal tien_ck_nt { get; set; }
        public decimal tien_ck { get; set; }
        public decimal ts_gtgt { get; set; }
        public decimal thue_gtgt_nt { get; set; }
        public decimal thue_gtgt { get; set; }
        public decimal tt_nt { get; set; }
        public decimal tt { get; set; }
        public string khuyen_mai { get; set; }
        public string tra_ck { get; set; }
        public string ma_nvkd { get; set; }
        public string ma_bp { get; set; }
        public string ma_phi { get; set; }
        public string tk_pt { get; set; }
        public string tk_dt { get; set; }
        public string tk_gv { get; set; }
        public string tk_vt { get; set; }
        public string tk_thue { get; set; }
        public string tk_ck { get; set; }
        public decimal sl_xuat { get; set; }
        public decimal sl_xuat_qd { get; set; }
        public decimal sl_hd { get; set; }
        public decimal sl_hd_qd { get; set; }
        public string ten_vt { get; set; }
        public string xlbm { get; set; }
        public string vat_lieu { get; set; }
        public decimal tgian_gc { get; set; }
        public string ten_nguoi_pt { get; set; }
        public string nguoi_pt { get; set; }
        public string nguoi_pt2 { get; set; }
        public string ten_nguoi_pt2 { get; set; }
        public string nguoi_pt3 { get; set; }
        public string ten_nguoi_pt3 { get; set; }
        public string ghi_chu { get; set; }
        public string so_lsx { get; set; }
        public string ten_vt2 { get; set; }
        public string ten_vat_lieu { get; set; }
        public string huy_ct { get; set; }
    }
}
